# R Markdown {#markdown}


## R Markdown vs Markdown

## Bookdown

These notes are written using the **bookdown** package [@R-bookdown], which was built on to
The **bookdown** package can be installed from CRAN or Github:

```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

Each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

### Publishing

These notes are published on GitHub Pages with GitHub Actions. The GitHub Action is triggered by a push to the master branch. The action first renders the repository's R Markdown files to HTML and deploys the HTML files as a static website to a branch called gh-pages. Alternatives to using GitHub Actions include Travis or Jekyll.

I used the steps outlined in the following blog post: 
<https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e> 
However, I did a lot of the git bash commands manually and there were two fixes I had to make to deploy_bookdown.yaml:

       with:
          build_dir: _book/
          email: ${{ secrets.EMAIL }}

under

uses: Cecilapp/GitHub-Pages-deploy@master

and GITHUB_TOKEN rather than GH_PAT as this is what GitHub-Pages-deploy now uses
<https://github.com/Cecilapp/GitHub-Pages-deploy>