# (PART) Power BI {.unnumbered}

# Power BI fundamentals

This Power BI section is likely to be superseded fairly soon by an MS Teams site being setup by Jess Kavanagh. The Teams site will help collate and disseminate the learning that has been shared by Giles Robinson, Sam Jenner, and others via the SCC **Power BI user group** coordinated by Paul Haine.

## What is Power BI?

Power BI is a tool for combining, analysing, and visualising data, and then sharing the results. It's a Microsoft product (originally an Excel add-in) that fits well with the Council's move to Microsoft Azure services. It's also reasonably priced compared to alternative tools such as Tableau (arguably a higher quality option).

Power BI is now the main Council tool for data analysis. Or rather, if you need something with more data analysis oomph than Excel, Power BI is probably the first tool you should consider. It's similar to ArcGIS being the main Council tool for spatial analysis.

The Council's Power BI comprises of three main pieces of software:

1.  Power BI desktop - local install, for designing reports (dashboards).
2.  Power BI report server - browser based internal report sharing.
3.  Power BI service - browser based non-confidential report sharing.

## Service

**Power BI service** has more functionality than the report server. The Council's Corporate Performance reporting is via Power BI service, but it doesn't include PID.

## Report server

The **Power BI report server** (<https://sccvmazpbi01.sheffield.gov.uk/reports>) is only available from within the Council's network. It is currently the default Council option for sharing your Power BI reports. Contact Keith Dunk to request a new folder on the Report Server and control of it.

Keep in mind that the Microsoft documentation is geared more towards using Power BI service.

You can upload a report and give permissions just to that report, but will need to share a link to the report. Unless you give them permission to the folder they cannot navigate to it, you can give *browser* access to the folder and the report so they can open it. Click the ... at the side of the folder name and select *manage* and then *security* (this is the same once you have reports uploaded). Permissions are added via user ID e.g. LP41455. User IDs can be found in the *Alias* field in the *Global Address List* in Outlook.

If you want to enable auto-refresh then you need to create the report using a URL not a drive mapping, Paul Haine can advise on this.

## Desktop

For version compatibility reasons, to upload reports to the report server you need to use the the May 2021 version of **Power BI desktop**. This version is available from the Council's Software Centre on your laptop. If you have a different version, remove it and install the Software Centre version.

## Roles

A consumer or **business user**, receives content (e.g. dashboards) from colleagues. *Business user* is the term used in Microsoft's Power BI documentation. Similarly, someone who creates content is called a **designer**. Other roles include **administrator** and *developer.*

The SCC **Power BI user group** that meets monthly is aimed at Power BI *designers* and *administrators* more than *business users*.

## Further resources

### For business users

Using Power BI reporting server: ...

Using Power BI service: [Explore what Power BI can do for you](https://docs.microsoft.com/en-gb/learn/modules/explore-power-bi-service/), a one hour online Microsoft learning module.

### For designers

A good way to quickly get familiar with Power BI is the free [Power BI Dashboard in a Day](https://powerbi.microsoft.com/en-us/diad/) online tutor-led workshop, indirectly provided by Microsoft.

[Create and use analytics reports with Power BI](https://docs.microsoft.com/en-us/learn/paths/create-use-analytics-reports-power-bi/) is a self-paced online Microsoft learning path.

Free e-book [Introducing Microsoft Power BI](https://download.microsoft.com/download/0/8/1/0816F8D1-D1A5-4F60-9AF5-BC91E18D6D64/Microsoft_Press_ebook_Introducing_Power_BI_PDF_mobile.pdf) by Alberto Ferrari & Marco Russo (2016).
