# R & RStudio {#r}

## Why script?

I initially started scripting in Python to automate some spatial analysis tasks, but soon realised that reproducibility was the main advantage. Iterating, improving a process incrementally and at the end verifying the results by re-running the script.

There's an element of self-documentation with scripting, so it's easier to return to a scripted task after a bit of time away from it, or pick up a scripted task from a colleague. However, in-line comments and adherence to a style guide make a big difference to just how easy it is. Version control and collaboration are also easier with scripting than GUI tools.

Scripting is not always better than using GUI tools. There's a good reason that more people use Mac OS and Windows than Unix Bash. Scripting or GUI tools is a horses for courses question, and some GUI workflow tools (e.g. FME, Simul8 and ModelBuilder in ArcGIS) sit somewhere in the middle.

## Style guide

Something I need to pay more attention to is following the [tidyverse style guide](https://style.tidyverse.org/), which benefits from supporting tools and familiarity via tidyverse package documentation.

Scripting to the same style guide makes collaboration easier. Which style guide is less important than collaborators scripting to the same style guide.

## RStudio security & data protection {#pid}

### Workspace {#workspace}

To encourage reproducible R scripts, Hadley Wickham recommends not preserving your workspace between sessions. This entails deselecting a couple of options to save and restore .Rdata (see [chapter 8 Workflow: projects](https://r4ds.had.co.nz/workflow-projects.html#what-is-real) in Hadley's R4DS book).

Hadley's recommendation also reduces the chances of inadvertently sharing PID in a GitHub repository. However, .Rdata should also be included in the [.gitignore](https://git-scm.com/docs/gitignore) file and the repository set to private.

### Passwords

It's poor practice to include login details in code. I use the `.Renviron` file option for [securing credentials](https://db.rstudio.com/best-practices/managing-credentials/#use-environment-variables). However, if I'm sharing the script I anticipate that the environment variable might not be set and use the RStudio API to prompt for credentials. For example:

```{r credentials, eval=FALSE}
if(is.null(portal_pwd = Sys.getenv("portal_pwd"))){
  portal_pwd = rstudioapi::askForPassword("Portal password")
}
```


## Getting started

I'm not going to provide advice on getting started, other than signposting to the excellent resources listed on the RStudio beginners page:

[RStudio Education - Beginners](https://education.rstudio.com/learn/beginner/)

## RStudio tips

### Code display  

*TODO*\  
- Rainbow braces  
- code line 80 


### Document outline and headings

*TODO*\  

### Pipe addin

*TODO*\  

### Shortcuts

Ctrl + Enter    run selected lines
Ctrl + Alt + P    re-run previous  

Ctrl + Alt + A    reformat code  

Alt + -   assignment operator <-
Ctrl + Shift + M    pipe operator %>%

*TODO*\  
%<>% 

*TODO*\
-   Write settings  
