# Python {#python}

Python and R are both popular data analysis scripting languages. Python is a general-purpose language with an easy-to-understand syntax. R's functionality was developed with statisticians in mind and is popular in academia and research.

## Reticulate

The [reticulate](https://rstudio.github.io/reticulate/) R package allows R to integrate with Python. RStudio v1.4 has embedded `reticulate` into the IDE. For example, you can define a default Python environment under Global Options or Project Options. You can also now inspect Python objects in the RStudio Environment pane.

## ArcGIS & API wrappers

The Council's ArcGIS software from ESRI has a much stronger integration with Python than R (see the section on [ArcGIS R & Python packages](#arcgisr) for further notes about this). Similarly, you may find Python packages but no corresponding R package for REST API "wrappers" that make it easier to obtain data (see the section on [wrappers](#wrappers) for further notes about this). In both cases, `reticulate` allows us to leverage Python packages from within R.
