# Python {#python}

## Reticulate

The [reticulate](https://rstudio.github.io/reticulate/) R package allows R to integrate with Python. RStudio has embedded `reticulate` into the IDE. For example, you can define a default Python environment under Global Options or Project Options. You can also now inspect Python objects in the RStudio Environment pane.

## ArcGIS & API wrappers

The Council's ArcGIS software from ESRI has a much stronger integration with Python than R (see the section on [ArcGIS R & Python packages](#arcgisr) for further notes about this). Similarly, you may find Python packages but no corresponding R package for REST API "wrappers" that make it easier to obtain data (see the section on [wrappers](#wrappers) for further notes about this). In both cases, `reticulate` allows us to leverage Python packages from within R.

## Spyder IDE

There are feature rich IDEs for working with Python such as PyCharm, RStudio and VS Code. At the other end of the feature scale is the default Python editor IDLE that is installed with every version of Python.  

Spyder is not as feature rich as many IDEs, but probably has more than enough to satisy your initial needs without being too complicated. Spyder installs as a Python package. This makes it a good option for working with ArcGIS via Python and the simplest solution for handling the ArcGIS licensing requirements and related Python package management. Installing Spyder requires cloning the default Python environment for ArcGIS Pro and adding Spyder using conda. Other IDEs can have issues handling virtual environments.
