# GIS with web & desktop tools

This section is aimed at Council data analysts with little or no experience of spatial data and GIS. GIS has traditionally been the domain of specialists and this is especially true in the Council. However, the Council's new web based GIS tools will open up GIS to a wider user base, with better opportunities for data analysts to make use of spatial data without being a GIS specialist.

## Web maps & dashboards

### ArcGIS {#arcgis}

The Council's Portal and AGOL are the default home for our spatial data. Similarly, if you're looking to not just extract spatial data, but to share it or share spatial analysis via a web map or dashboard, then the default tool is also the Council's Portal and AGOL. To share content on Portal or AGOL you need a Creator license.

Anne Tetley has provided the following guidance (on Portal) about creating content in Portal and AGOL:

-   [Creating a web map in Portal](https://sheffieldcitycouncil.cloud.esriuk.com/portal/apps/storymaps/stories/47a2818d4a0442e9ac62eaa98621e30d)

-   [Creating a Web Application](https://sheffieldcitycouncil.cloud.esriuk.com/portal/apps/storymaps/stories/ffb57414e4454521bf578cd7bf04d6c2)

### Power BI

The GIS capabilities of Power BI do not match Portal or AGOL. However, if only a small proportion of the analysis you are sharing is spatial, then Power BI could be a good option. The ArcGIS Power BI integration tool is available to us. Anne Tetley has provided the following guidance (on Portal):

-   [ArcGIS for Power BI](https://sheffieldcitycouncil.cloud.esriuk.com/portal/apps/storymaps/stories/622f381b377c4607902064fd311a84f1)

## Desktop GIS

For some specialised spatial analysis a desktop GIS is best. However, as we move to sharing spatial information using web maps and dashboards, rather than static PDF maps, desktop GIS is increasingly a tool for GIS specialists.

### ArcGIS Desktop

For the last fifteen, twenty years, the Council's spatial analysis has largely been done using ArcGIS Desktop from ESRI. This is a powerful piece of software, but for the majority of GIS uses, it's a sledge hammer to crack a nut. If you've not done spatial analysis before, the recommendation is to first try our new, far more intuitive, ArcGIS web GIS tools i.e. our Portal and AGOL.

ESRI have stopped development of ArcGIS Desktop, though it won't be retired for some years yet. New functionality will only be added to ArcGIS Pro from now on.

### ArcGIS Pro

ArcGIS Pro is another desktop GIS application from ESRI. It isn't as old as ArcGIS Desktop, so has less legacy issues. ArcGIS Pro is 64-bit and is more closely integrated with the ArcGIS Enterprise (Portal) and AGOL. However, the single biggest difference is that the hundreds of nested menu driven options are located in different places to ArcGIS Desktop!

The Council has an ArcGIS Pro license for every purchased ArcGIS Desktop license.

### QGIS

QGIS is an open source alternative to ArcGIS Desktop and ArcGIS Pro.

## Further resources

*TODO - cross-ref database chapter and spatial database content*
