---
title: "pinsheff"
author: "Laurie Platt"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::bs4_book
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: scc-pi/notes
description: "Some notes, examples, lessons learnt and links to further resources."
favicon: images/favicon.ico
---

# About {.unnumbered}

Welcome to Performance & Intelligence Notes for Sheffield City Council, or **pinsheff** for short. Data Analysis Notes for Sheffield City Council might have been a better name, but we've already got a couple of Dans in the team.

This is a place for ad-hoc notes, mainly to do with scripting and mainly R scripts. It's somewhere to store lessons learnt and examples. A resource to remind yourself if you return to something after a while away from it, or to smooth your path a little if it's something new.

There are many excellent online resources that these notes will point to and will not attempt to replace. Overtime some notes may mature into package vignettes or become accepted as good practice and included in the [Methods Manual](https://scc-pi.github.io/methods-manual/).

Hopefully, others from the Performance & Intelligence Team, or elsewhere in Sheffield City Council, will contribute to these notes. However, currently it's just one person and is biased to one person's recent experience: ETL, geocoding and spatial analysis. Notes about modelling and visualisations are lacking.

As well as the contributors and content, the purpose and scope is open to change. I hope you find the notes useful.